### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by Karh3030** [vadymfedorets/CatsvsDogs#13]
ДД, Вадим, ошибка уже недели 1.5:
Unknown error while verifying task 43 | Error: 403, message='Forbidden', url=URL('https://api.catsdogs.live/tasks/claim')
В чате хидденкода она упоминалась уже.

**Comment by dsadwqeqeasad** [comment]
Ошибка и в приложении, можешь сам попробовать забрать таску джоин мемефай ченел
