### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MelikUltra** [vadymfedorets/CatsvsDogs#3]
> 1
Cats&Dogs | 2024-09-25 22:38:28 | INFO     | 54 - Searched sessions: 1.
Cats&Dogs | 2024-09-25 22:38:28 | SUCCESS  | 64 - Available accounts: 1.
Cats&Dogs | 2024-09-25 22:38:28 | INFO     | 261 - Melik | Start delay 3 seconds
Cats&Dogs | 2024-09-25 22:38:32 | ERROR    | 95 - Melik | Unknown error during Authorization: list index out of range
Cats&Dogs | 2024-09-25 22:38:35 | ERROR    | 95 - Melik | Unknown error during Authorization: list index out of range
Cats&Dogs | 2024-09-25 22:38:41 | INFO     | 281 - Melik | Balance: 1782 $FOOD
Cats&Dogs | 2024-09-25 22:38:51 | INFO     | 167 - Melik | Performing TG subscription to https://t.me/catsdogs_community
Cats&Dogs | 2024-09-25 22:38:51 | INFO     | 137 - Melik | Get channel: catsdogs_community
Cats&Dogs | 2024-09-25 22:38:52 | INFO     | 142 - Melik | User not participant of the TG group: catsdogs_community
Cats&Dogs | 2024-09-25 22:38:55 | INFO     | 145 - Melik | Joined to channel: catsdogs_community
Task exception was never retrieved
future: <Task finished name='Task-108' coro=<Client.handle_updates() done, defined at C:\Users\ULTRA\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\client.py:612> exception=ProgrammingError('Cannot operate on a closed database.')>
Traceback (most recent call last):
  File "C:\Users\ULTRA\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\client.py", line 617, in handle_updates
    await self.fetch_peers(updates.users),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ULTRA\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\client.py", line 607, in fetch_peers
    await self.storage.update_peers(parsed_peers)
  File "C:\Users\ULTRA\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\storage\sqlite_storage.py", line 159, in update_peers
    self.conn.executemany(
sqlite3.ProgrammingError: Cannot operate on a closed database.
Cats&Dogs | 2024-09-25 22:38:55 | SUCCESS  | 175 - Melik | Task Join our community completed! | Reward: +300 FOOD

**Comment by vadymfedorets** [comment]
session issue, try reloading script and if it repeats recreation of session

**Comment by vadymfedorets** [comment]
https://github.com/vadymfedorets/CatsvsDogs/issues/2

**Comment by MelikUltra** [comment]
> #2

the thing is, this session dosent have any issue in other 30+ python bots

**Comment by vadymfedorets** [comment]
I cannot reproduce bug on more than 100 accounts.
